(clear)
(watch compilations)
(load global.clp)
(load func.clp)
(load main.clp)
(load yes.clp)
(load no.clp)
(load cse.clp)
(load ece.clp)
(load mech.clp)
(load softwares.clp)
(reset)
(run)
